In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import time
%matplotlib inline
import numpy as np

In [4]:
merged = pd.read_csv('merg_data.csv')

In [5]:
merged.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,Ent,Ext,day_of_week,month
0,0,1,1,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,07:00:00,REGULAR,6527794,2210507,14.0,11.0,Saturday,2
1,1,2,2,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,11:00:00,REGULAR,6527838,2210585,44.0,78.0,Saturday,2
2,2,3,3,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,15:00:00,REGULAR,6527994,2210644,156.0,59.0,Saturday,2
3,3,4,4,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,19:00:00,REGULAR,6528278,2210705,284.0,61.0,Saturday,2
4,4,5,5,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,23:00:00,REGULAR,6528389,2210728,111.0,23.0,Saturday,2

In [6]:
merged_data = merged.dropna(axis=0)

In [6]:
merged_data.to_csv('merg_data.csv')

In [7]:
merged_data['Ent'].value_counts()

 0.0            453814
 1.0             52978
 2.0             38542
 3.0             34160
 4.0             31567
 5.0             29475
 6.0             28198
 7.0             26821
 8.0             26192
 9.0             24714
 10.0            23924
 11.0            23260
 12.0            22349
 13.0            21643
 14.0            21326
 15.0            20303
 16.0            19514
 17.0            18957
 18.0            18387
 19.0            17744
 20.0            17189
 21.0            16628
 22.0            16184
 23.0            15747
 24.0            15276
 25.0            14771
 26.0            14432
 27.0            14113
 28.0            13844
 29.0            13226
                 ...
-4286414.0           1
 4286577.0           1
 4286810.0           1
-4287040.0           1
 4287530.0           1
 4287647.0           1
 4287767.0           1
-4287814.0           1
 4287875.0           1
-4288408.0           1
 4288553.0           1
 4285164.0           1
-4284896.0           1
-4284880.0           1
 4283189.0           1
 4282173.0           1
 16728.0             1
 4282448.0           1
 4282738.0           1
 4282820.0           1
-4282900.0           1
 4283555.0           1
-16737.0             1
-4283605.0           1
 4283618.0           1
-4283635.0           1
 4283941.0           1
-4284277.0           1
 4284337.0           1
 616793335.0         1
Name: Ent, Length: 77687, dtype: int64

In [8]:
merged_data.describe()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,ENTRIES,EXITS,Ent,Ext,month
count,3.154760e+06,3.154760e+06,3.154760e+06,3.154760e+06,3.154760e+06,3.154760e+06,3.154760e+06,3.154760e+06
mean,1.577380e+06,1.577380e+06,9.858794e+04,3.927403e+07,3.232718e+07,-1.139037e+00,-5.779330e-01,4.177458e+00
std,9.107009e+05,9.107009e+05,5.692249e+04,2.050674e+08,1.900460e+08,4.288098e+07,3.929465e+07,1.111800e+00
min,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-2.117750e+09,-2.145033e+09,2.000000e+00
25%,7.886898e+05,7.886908e+05,4.929300e+04,5.081948e+05,2.482708e+05,9.000000e+00,7.000000e+00,3.000000e+00
50%,1.577380e+06,1.577380e+06,9.858600e+04,2.577975e+06,1.454429e+06,7.400000e+01,5.100000e+01,4.000000e+00
75%,2.366069e+06,2.366070e+06,1.478790e+05,6.890224e+06,4.826487e+06,2.510000e+02,1.700000e+02,5.000000e+00
max,3.154759e+06,3.154760e+06,1.991150e+05,2.130068e+09,2.145850e+09,2.122404e+09,2.145033e+09,6.000000e+00

In [9]:
merged_data.drop('Unnamed: 0', axis=1, inplace=True)

In [10]:
merged_data.drop('Unnamed: 0.1', axis=1, inplace=True)

In [12]:
merged_data.drop('Unnamed: 0.1.1', axis=1, inplace=True)

In [13]:
merged_data.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,Ent,Ext,day_of_week,month
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,07:00:00,REGULAR,6527794,2210507,14.0,11.0,Saturday,2
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,11:00:00,REGULAR,6527838,2210585,44.0,78.0,Saturday,2
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,15:00:00,REGULAR,6527994,2210644,156.0,59.0,Saturday,2
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,19:00:00,REGULAR,6528278,2210705,284.0,61.0,Saturday,2
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,23:00:00,REGULAR,6528389,2210728,111.0,23.0,Saturday,2

In [14]:
q25, q50, q75 = np.percentile(merged_data['Ext'],[25,50,75])
iqr=q75-q25
min=q25 -1.5*(iqr)
max=q75 +1.5*(iqr)

print(min, q25, q50, q75, max)

-237.5 7.0 51.0 170.0 414.5

In [15]:
[x for x in merged_data['Ent'] if x>max]

[750.0,
 784.0,
 748.0,
 729.0,
 650.0,
 530.0,
 579.0,
 582.0,
 570.0,
 544.0,
 514.0,
 572.0,
 562.0,
 521.0,
 480.0,
 5074409.0,
 572.0,
 611.0,
 579.0,
 586.0,
 542.0,
 532.0,
 551.0,
 576.0,
 541.0,
 504.0,
 1316176.0,
 547.0,
 615.0,
 594.0,
 557.0,
 585.0,
 4030879.0,
 428.0,
 419.0,
 757.0,
 425.0,
 858.0,
 849.0,
 424.0,
 427.0,
 837.0,
 696.0,
 451.0,
 704.0,
 486.0,
 784.0,
 467.0,
 741.0,
 455.0,
 810.0,
 420.0,
 625.0,
 7413911.0,
 431.0,
 428.0,
 470.0,
 478.0,
 429.0,
 758.0,
 461.0,
 804.0,
 782.0,
 451.0,
 823.0,
 520.0,
 614.0,
 1184677.0,
 736.0,
 442.0,
 786.0,
 768.0,
 450.0,
 716.0,
 539.0,
 578.0,
 1244224.0,
 587.0,
 583.0,
 563.0,
 554.0,
 466.0,
 456.0,
 496.0,
 479.0,
 460.0,
 4704812.0,
 419.0,
 425.0,
 437.0,
 415.0,
 1335209.0,
 567.0,
 656.0,
 612.0,
 583.0,
 481.0,
 445.0,
 766.0,
 490.0,
 845.0,
 519.0,
 836.0,
 479.0,
 791.0,
 548.0,
 640.0,
 12015743.0,
 630.0,
 1050.0,
 734.0,
 1101.0,
 753.0,
 1015.0,
 707.0,
 1037.0,
 748.0,
 807.0,
 3299605.0,
 115457616.0,
 550.0,
 712.0,
 643.0,
 585.0,
 436.0,
 517.0,
 2279029.0,
 425.0,
 540.0,
 443.0,
 605.0,
 447.0,
 592.0,
 426.0,
 531.0,
 446.0,
 512.0,
 447.0,
 520.0,
 498.0,
 522.0,
 422.0,
 1016.0,
 735.0,
 880.0,
 744.0,
 1639.0,
 717.0,
 480.0,
 1082.0,
 752.0,
 941.0,
 556.0,
 11120698.0,
 799.0,
 495.0,
 598.0,
 450.0,
 1103.0,
 469.0,
 793.0,
 514.0,
 695.0,
 579.0,
 482.0,
 893.0,
 651.0,
 552.0,
 584.0,
 583.0,
 811.0,
 603.0,
 506.0,
 723896.0,
 775.0,
 827.0,
 1055.0,
 762.0,
 617.0,
 481.0,
 1035.0,
 523.0,
 1226.0,
 532.0,
 1479.0,
 548.0,
 1063.0,
 496.0,
 799.0,
 16801950.0,
 513.0,
 719.0,
 437.0,
 534.0,
 473.0,
 584.0,
 1401.0,
 753.0,
 524.0,
 692.0,
 1654.0,
 769.0,
 489.0,
 2130.0,
 727.0,
 527.0,
 616.0,
 1478.0,
 690.0,
 432.0,
 490.0,
 1135.0,
 444.0,
 11390582.0,
 450.0,
 885.0,
 1143.0,
 766.0,
 654.0,
 918.0,
 605.0,
 945.0,
 1043.0,
 1953.0,
 1219.0,
 1025.0,
 1218.0,
 2065.0,
 1247.0,
 1015.0,
 3142.0,
 1212.0,
 962.0,
 1095.0,
 2035.0,
 1166.0,
 823.0,
 918.0,
 1612.0,
 759.0,
 857290851.0,
 555.0,
 465.0,
 1264.0,
 553.0,
 444.0,
 1297.0,
 680.0,
 439.0,
 1296.0,
 652.0,
 444.0,
 1277.0,
 659.0,
 1283.0,
 459.0,
 1545664671.0,
 963.0,
 1026.0,
 459.0,
 1008.0,
 451.0,
 1024.0,
 462.0,
 983.0,
 100291700.0,
 880.0,
 993.0,
 897.0,
 917.0,
 430.0,
 936.0,
 426.0,
 1224.0,
 522.0,
 1186.0,
 553.0,
 1219.0,
 537.0,
 1178.0,
 558.0,
 1218.0,
 499.0,
 1144732.0,
 589.0,
 442.0,
 1640.0,
 765.0,
 468.0,
 1606.0,
 796.0,
 483.0,
 1626.0,
 764.0,
 475.0,
 1573.0,
 803.0,
 503.0,
 1623.0,
 665.0,
 4577339.0,
 650.0,
 678.0,
 537.0,
 667.0,
 605.0,
 1166198.0,
 771.0,
 770.0,
 437.0,
 702.0,
 814.0,
 451.0,
 792.0,
 425.0,
 1127.0,
 599.0,
 1077.0,
 677.0,
 939.0,
 628.0,
 1087.0,
 628.0,
 1165.0,
 475.0,
 2313494.0,
 424.0,
 422.0,
 816.0,
 792.0,
 548.0,
 785.0,
 583.0,
 810.0,
 572.0,
 726.0,
 449.0,
 4101796.0,
 542.0,
 560.0,
 603.0,
 530.0,
 491.0,
 11608296.0,
 985.0,
 435.0,
 1036.0,
 541.0,
 426.0,
 1004.0,
 468.0,
 451.0,
 1120.0,
 520.0,
 600.0,
 856.0,
 942.0,
 481.0,
 820.0,
 427.0,
 961.0,
 419.0,
 1090.0,
 445.0,
 712.0,
 801.0,
 769.0,
 763.0,
 885.0,
 4993296.0,
 578.0,
 681.0,
 624.0,
 603.0,
 774.0,
 464.0,
 487.0,
 525.0,
 500.0,
 498.0,
 436.0,
 452.0,
 457.0,
 516.0,
 478.0,
 583.0,
 461.0,
 562.0,
 1699109.0,
 629.0,
 630.0,
 664.0,
 638.0,
 633.0,
 8884684.0,
 425.0,
 574.0,
 427.0,
 436.0,
 800.0,
 447.0,
 793.0,
 507.0,
 815.0,
 439.0,
 843.0,
 573.0,
 820.0,
 478.0,
 65881335.0,
 514.0,
 461.0,
 668.0,
 542.0,
 1461.0,
 831.0,
 586.0,
 561.0,
 1474.0,
 823.0,
 616.0,
 592.0,
 1556.0,
 836.0,
 594.0,
 580.0,
 1342.0,
 768.0,
 520.0,
 1407.0,
 589.0,
 446.0,
 1200.0,
 489.0,
 442.0,
 1206.0,
 535.0,
 453.0,
 1233.0,
 514.0,
 433.0,
 1257.0,
 537.0,
 1178.0,
 946.0,
 929.0,
 939.0,
 983.0,
 913.0,
 121352.0,
 858.0,
 882.0,
 880.0,
 871.0,
 820.0,
 730.0,
 680.0,
 667.0,
 672.0,
 622.0,
 560.0,
 510.0,
 564.0,
 558.0,
 550.0,
 104504.0,
 856.0,
 869.0,
 808.0,
 837.0,
 798.0,
 617385.0,
 1495.0,
 574.0,
 1564.0,
 659.0,
 1428.0,
 623.0,
 428.0,
 1466.0,
 544.0,
 1396.0,
 22804177.0,
 704.0,
 1075.0,
 715.0,
 453.0,
 763.0,
 507.0,
 464.0,
 854.0,
 2293.0,
 1293.0,
 479.0,
 936.0,
 2374.0,
 1360.0,
 452.0,
 939.0,
 2222.0,
 1317.0,
 485.0,
 936.0,
 2266.0,
 1201.0,
 471.0,
 843.0,
 1980.0,
 860.0,
 280229.0,
 605.0,
 953.0,
 647.0,
 626.0,
 456.0,
 422.0,
 701.0,
 1888.0,
 952.0,
 784.0,
 2002.0,
 1064.0,
 428.0,
 681.0,
 1968.0,
 1045.0,
 778.0,
 2019.0,
 990.0,
 656.0,
 1759.0,
 588.0,
 728.0,
 1006.0,
 650.0,
 741.0,
 438.0,
 417.0,
 887.0,
 1997.0,
 1047.0,
 499.0,
 883.0,
 2030.0,
 1259.0,
 503.0,
 870.0,
 2127.0,
 1223.0,
 548.0,
 869.0,
 2055.0,
 1038.0,
 833.0,
 1846.0,
 736.0,
 54483446.0,
 453.0,
 681.0,
 684.0,
 691.0,
 611.0,
 656.0,
 440.0,
 470.0,
 1007.0,
 486.0,
 437.0,
 999.0,
 473.0,
 1075.0,
 532.0,
 949.0,
 472.0,
 753.0,
 7516353.0,
 460.0,
 591.0,
 496.0,
 493.0,
 925.0,
 494.0,
 1379.0,
 678.0,
 938.0,
 549.0,
 1385.0,
 722.0,
 937.0,
 508.0,
 1386.0,
 761.0,
 636.0,
 526.0,
 1361.0,
 664.0,
 559.0,
 436.0,
 1150.0,
 506.0,
 1194457.0,
 450.0,
 572.0,
 497.0,
 468.0,
 931.0,
 472.0,
 1402.0,
 689.0,
 1040.0,
 466.0,
 1433.0,
 666.0,
 1047.0,
 457.0,
 1457.0,
 709.0,
 665.0,
 484.0,
 1361.0,
 645.0,
 603.0,
 430.0,
 1211.0,
 506.0,
 495.0,
 616.0,
 468.0,
 823.0,
 444.0,
 1367.0,
 634.0,
 876.0,
 1349.0,
 670.0,
 852.0,
 1420.0,
 742.0,
 577.0,
 433.0,
 1327.0,
 741.0,
 525.0,
 437.0,
 1333.0,
 552.0,
 436.0,
 737.0,
 705.0,
 529.0,
 455.0,
 866.0,
 469.0,
 1451.0,
 795.0,
 837.0,
 460.0,
 1497.0,
 895.0,
 834.0,
 483.0,
 1579.0,
 868.0,
 573.0,
 508.0,
 1510.0,
 944.0,
 530.0,
 547.0,
 1500.0,
 763.0,
 1234183032.0,
 314915461.0,
 894.0,
 726.0,
 963.0,
 704.0,
 1011.0,
 691.0,
 989.0,
 565.0,
 744.0,
 463.0,
 3823065.0,
 476.0,
 780.0,
 632.0,
 759.0,
 552.0,
 934.0,
 700.0,
 433.0,
 837.0,
 618.0,
 676.0,
 466.0,
 70826197.0,
 502.0,
 537.0,
 530.0,
 506.0,
 500.0,
 783.0,
 751.0,
 562.0,
 769.0,
 431.0,
 788.0,
 2211435.0,
 804.0,
 814.0,
 560.0,
 807.0,
 824.0,
 597.0,
 642.0,
 464.0,
 638.0,
 655.0,
 582360.0,
 500.0,
 556.0,
 592.0,
 578.0,
 189212.0,
 461.0,
 448.0,
 525.0,
 551.0,
 1645740.0,
 447.0,
 1946368.0,
 783.0,
 677.0,
 593.0,
 648.0,
 644.0,
 1025190.0,
 626.0,
 638.0,
 638.0,
 707.0,
 712.0,
 547.0,
 727.0,
 440.0,
 808.0,
 453.0,
 773.0,
 481.0,
 756.0,
 2770731.0,
 727.0,
 817.0,
 464.0,
 688.0,
 440.0,
 741.0,
 481.0,
 693.0,
 526.0,
 546.0,
 523.0,
 567.0,
 516.0,
 491.0,
 534.0,
 416.0,
 560.0,
 496.0,
 1129601.0,
 777.0,
 778.0,
 745.0,
 1242.0,
 667.0,
 1196.0,
 3140055.0,
 452.0,
 1109.0,
 519.0,
 1221.0,
 609.0,
 1070.0,
 580.0,
 1894.0,
 1256.0,
 584.0,
 743.0,
 1931.0,
 728.0,
 480611.0,
 519.0,
 702.0,
 528.0,
 498.0,
 638.0,
 1579.0,
 961.0,
 544.0,
 658.0,
 1657.0,
 1018.0,
 559.0,
 739.0,
 1599.0,
 984.0,
 562.0,
 673.0,
 474.0,
 858.0,
 477.0,
 501.0,
 903.0,
 499.0,
 511.0,
 420.0,
 825.0,
 498.0,
 526.0,
 903.0,
 545.0,
 497.0,
 447.0,
 948.0,
 77556176.0,
 635.0,
 698.0,
 616.0,
 703.0,
 718.0,
 422.0,
 555.0,
 431.0,
 1194.0,
 721.0,
 489.0,
 1212.0,
 761.0,
 449.0,
 1192.0,
 666.0,
 506.0,
 1130.0,
 733.0,
 456.0,
 1086.0,
 496.0,
 3642514.0,
 881.0,
 477.0,
 951.0,
 533.0,
 865.0,
 519.0,
 848.0,
 479.0,
 786.0,
 2099810.0,
 688.0,
 696.0,
 694.0,
 667.0,
 673.0,
 1134163.0,
 433.0,
 513.0,
 444.0,
 454.0,
 752.0,
 792.0,
 766.0,
 787.0,
 444.0,
 740.0,
 724.0,
 698.0,
 676.0,
 594.0,
 667.0,
 1236.0,
 1206.0,
 1153.0,
 1223.0,
 439.0,
 438.0,
 1013.0,
 12234016.0,
 441.0,
 498.0,
 434.0,
 419.0,
 1456.0,
 423.0,
 480.0,
 1403.0,
 582.0,
 489.0,
 1364.0,
 514.0,
 506.0,
 1346.0,
 600.0,
 477.0,
 1176.0,
 723.0,
 777.0,
 509.0,
 431.0,
 679.0,
 656.0,
 1775.0,
 684.0,
 734.0,
 1914.0,
 875.0,
 773.0,
 1861.0,
 842.0,
 733.0,
 1814.0,
 886.0,
 760.0,
 1568.0,
 1182.0,
 1160.0,
 742.0,
 707.0,
 942.0,
 440.0,
 1036.0,
 2469.0,
 945.0,
 421.0,
 1136.0,
 2557.0,
 1161.0,
 481.0,
 1225.0,
 2518.0,
 1157.0,
 1149.0,
 2568.0,
 1141.0,
 1099.0,
 2096.0,
 10267466.0,
 733.0,
 1471.0,
 906.0,
 959.0,
 1194.0,
 642.0,
 832.0,
 1443.0,
 2613.0,
 1187.0,
 1005.0,
 1474.0,
 2802.0,
 1327.0,
 1014.0,
 1461.0,
 2899.0,
 1438.0,
 1043.0,
 1647.0,
 2840.0,
 1330.0,
 892.0,
 1499.0,
 2186.0,
 68145719.0,
 428.0,
 1335.0,
 420.0,
 480.0,
 1408.0,
 457.0,
 468.0,
 1386.0,
 495.0,
 480.0,
 1395.0,
 1103.0,
 567.0,
 530.0,
 606.0,
 489.0,
 2787867.0,
 673.0,
 622.0,
 515.0,
 663.0,
 1209.0,
 478.0,
 654.0,
 1199.0,
 528.0,
 771.0,
 ...]

In [16]:
merged_data.loc[merged_data['Ent'] < 0]

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,Ent,Ext,day_of_week,month
41,A002,R051,02-00-01,59 ST,NQR456W,BMT,2018-02-24,03:00:00,RECOVR AUD,5859014,1308342,-6.767520e+05,-9.050000e+05,Saturday,2
83,A002,R051,02-03-00,59 ST,NQR456W,BMT,2018-02-24,03:00:00,RECOVR AUD,1043482,3875067,-4.821694e+06,2.565003e+06,Saturday,2
125,A002,R051,02-03-01,59 ST,NQR456W,BMT,2018-02-24,03:00:00,RECOVR AUD,607855,945001,-4.382700e+05,-2.942091e+06,Saturday,2
209,A002,R051,02-03-03,59 ST,NQR456W,BMT,2018-02-24,03:00:00,RECOVR AUD,5294678,6196954,-4.023820e+05,-1.583673e+06,Saturday,2
335,A002,R051,02-03-06,59 ST,NQR456W,BMT,2018-02-24,03:00:00,RECOVR AUD,8379626,488552,-2.288923e+06,-8.604310e+05,Saturday,2
377,A002,R051,02-05-00,59 ST,NQR456W,BMT,2018-02-24,03:00:00,RECOVR AUD,1473,0,-8.388326e+06,-4.886790e+05,Saturday,2
419,A002,R051,02-05-01,59 ST,NQR456W,BMT,2018-02-24,03:00:00,RECOVR AUD,0,758,-1.480000e+03,7.580000e+02,Saturday,2
503,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,2018-02-24,01:00:00,REGULAR,3243542,5507292,-4.176519e+06,5.349723e+06,Saturday,2
632,A006,R079,00-00-03,5 AV/59 ST,NQRW,BMT,2018-02-24,01:00:00,REGULAR,2578533,949063,-3.117597e+06,-1.531896e+07,Saturday,2
761,A006,R079,00-03-01,5 AV/59 ST,NQRW,BMT,2018-02-24,01:00:00,REGULAR,2763769,1472498,-5.870755e+06,-2.343135e+06,Saturday,2
847,A007,R079,01-05-00,5 AV/59 ST,NQRW,BMT,2018-02-24,01:00:00,REGULAR,3126,0,-1.479758e+07,-1.521071e+07,Saturday,2
889,A007,R079,01-05-01,5 AV/59 ST,NQRW,BMT,2018-02-24,01:00:00,REGULAR,1,1226,-3.134000e+03,1.226000e+03,Saturday,2
1015,A007,R079,01-06-02,5 AV/59 ST,NQRW,BMT,2018-02-24,01:00:00,REGULAR,4437822,1855187,-1.143300e+08,-1.220270e+05,Saturday,2
1099,A010,R080,00-00-00,57 ST-7 AV,NQRW,BMT,2018-02-24,03:00:00,RECOVR AUD,3118883,1388630,-3.611616e+06,-1.141997e+06,Saturday,2
1181,A010,R080,00-00-02,57 ST-7 AV,NQRW,BMT,2018-02-24,03:00:00,RECOVR AUD,10374205,4037231,-3.891983e+06,-1.297441e+06,Saturday,2
1222,A010,R080,00-00-03,57 ST-7 AV,NQRW,BMT,2018-02-24,03:00:00,RECOVR AUD,2931135,1452439,-7.451338e+06,-2.589610e+06,Saturday,2
1304,A010,R080,00-00-05,57 ST-7 AV,NQRW,BMT,2018-02-24,03:00:00,RECOVR AUD,586666,167694,-3.084945e+06,-1.704631e+06,Saturday,2
1428,A011,R080,01-00-00,57 ST-7 AV,NQRW,BMT,2018-02-24,07:00:00,REGULAR,886136890,491714887,-7.700000e+01,-1.160000e+02,Saturday,2
1429,A011,R080,01-00-00,57 ST-7 AV,NQRW,BMT,2018-02-24,11:00:00,REGULAR,886136644,491714336,-2.460000e+02,-5.510000e+02,Saturday,2
1430,A011,R080,01-00-00,57 ST-7 AV,NQRW,BMT,2018-02-24,15:00:00,REGULAR,886136165,491713667,-4.790000e+02,-6.690000e+02,Saturday,2
1431,A011,R080,01-00-00,57 ST-7 AV,NQRW,BMT,2018-02-24,19:00:00,REGULAR,886135507,491712996,-6.580000e+02,-6.710000e+02,Saturday,2
1432,A011,R080,01-00-00,57 ST-7 AV,NQRW,BMT,2018-02-24,23:00:00,REGULAR,886135014,491712602,-4.930000e+02,-3.940000e+02,Saturday,2
1433,A011,R080,01-00-00,57 ST-7 AV,NQRW,BMT,2018-02-25,03:00:00,REGULAR,886134732,491712549,-2.820000e+02,-5.300000e+01,Sunday,2
1434,A011,R080,01-00-00,57 ST-7 AV,NQRW,BMT,2018-02-25,07:00:00,REGULAR,886134682,491712457,-5.000000e+01,-9.200000e+01,Sunday,2
1435,A011,R080,01-00-00,57 ST-7 AV,NQRW,BMT,2018-02-25,11:00:00,REGULAR,886134488,491712040,-1.940000e+02,-4.170000e+02,Sunday,2
1436,A011,R080,01-00-00,57 ST-7 AV,NQRW,BMT,2018-02-25,15:00:00,REGULAR,886134080,491711488,-4.080000e+02,-5.520000e+02,Sunday,2
1437,A011,R080,01-00-00,57 ST-7 AV,NQRW,BMT,2018-02-25,19:00:00,REGULAR,886133505,491710959,-5.750000e+02,-5.290000e+02,Sunday,2
1438,A011,R080,01-00-00,57 ST-7 AV,NQRW,BMT,2018-02-25,23:00:00,REGULAR,886133133,491710780,-3.720000e+02,-1.790000e+02,Sunday,2
1439,A011,R080,01-00-00,57 ST-7 AV,NQRW,BMT,2018-02-26,03:00:00,REGULAR,886133005,491710744,-1.280000e+02,-3.600000e+01,Monday,2
1440,A011,R080,01-00-00,57 ST-7 AV,NQRW,BMT,2018-02-26,07:00:00,REGULAR,886132949,491710563,-5.600000e+01,-1.810000e+02,Monday,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3153066,R730,R431,00-00-04,EASTCHSTER/DYRE,5,IRT,2018-06-14,17:00:00,REGULAR,1560092765,1728116000,-8.800000e+01,5.700000e+01,Thursday,6
3153067,R730,R431,00-00-04,EASTCHSTER/DYRE,5,IRT,2018-06-14,21:00:00,REGULAR,1560092689,1728116096,-7.600000e+01,9.600000e+01,Thursday,6
3153068,R730,R431,00-00-04,EASTCHSTER/DYRE,5,IRT,2018-06-15,01:00:00,REGULAR,1560092682,1728116119,-7.000000e+00,2.300000e+01,Friday,6
3153069,R730,R431,00-00-04,EASTCHSTER/DYRE,5,IRT,2018-06-15,05:00:00,REGULAR,1560092678,1728116124,-4.000000e+00,5.000000e+00,Friday,6
3153070,R730,R431,00-00-04,EASTCHSTER/DYRE,5,IRT,2018-06-15,09:00:00,REGULAR,1560092468,1728116144,-2.100000e+02,2.000000e+01,Friday,6
3153071,R730,R431,00-00-04,EASTCHSTER/DYRE,5,IRT,2018-06-15,13:00:00,REGULAR,1560092419,1728116166,-4.900000e+01,2.200000e+01,Friday,6
3153072,R730,R431,00-00-04,EASTCHSTER/DYRE,5,IRT,2018-06-15,17:00:00,REGULAR,1560092350,1728116199,-6.900000e+01,3.300000e+01,Friday,6
3153073,R730,R431,00-00-04,EASTCHSTER/DYRE,5,IRT,2018-06-15,21:00:00,REGULAR,1560092304,1728116251,-4.600000e+01,5.200000e+01,Friday,6
3153074,S101,R070,00-00-00,ST. GEORGE,1,SRT,2018-06-09,00:00:00,REGULAR,1222353,192,-1.558870e+09,-1.728116e+09,Saturday,6
3153116,S101,R070,00-00-01,ST. GEORGE,1,SRT,2018-06-09,00:00:00,REGULAR,1099483,116,-1.263630e+05,-7.600000e+01,Saturday,6
3153158,S101,R070,00-00-02,ST. GEORGE,1,SRT,2018-06-09,00:00:00,REGULAR,952241,90,-1.503730e+05,-2.600000e+01,Saturday,6
3153200,S101,R070,00-00-03,ST. GEORGE,1,SRT,2018-06-09,00:00:00,REGULAR,835767,62,-1.191600e+05,-2.800000e+01,Saturday,6
3153242,S101,R070,00-00-04,ST. GEORGE,1,SRT,2018-06-09,00:00:00,REGULAR,777404,61,-6.075700e+04,-1.000000e+00,Saturday,6
3153284,S101,R070,00-00-05,ST. GEORGE,1,SRT,2018-06-09,00:00:00,REGULAR,502235,27,-2.774150e+05,-3.400000e+01,Saturday,6
3153368,S101,R070,00-00-07,ST. GEORGE,1,SRT,2018-06-09,00:00:00,REGULAR,670787,122,-1.292298e+06,-8.216000e+03,Saturday,6
3153494,S101,R070,00-03-01,ST. GEORGE,1,SRT,2018-06-09,00:00:00,REGULAR,1356115,96,-3.175119e+06,-4.393000e+03,Saturday,6
3153536,S101,R070,00-03-02,ST. GEORGE,1,SRT,2018-06-09,00:00:00,REGULAR,1326358,93,-3.454400e+04,-3.000000e+00,Saturday,6
3153704,S101A,R070,01-00-02,ST. GEORGE,1,SRT,2018-06-09,00:00:00,REGULAR,3244806,20237,-8.086216e+07,1.689100e+04,Saturday,6
3153746,S101A,R070,01-00-03,ST. GEORGE,1,SRT,2018-06-09,00:00:00,REGULAR,2361835,412,-8.852870e+05,-1.982500e+04,Saturday,6
3153788,S101A,R070,01-00-04,ST. GEORGE,1,SRT,2018-06-09,00:00:00,REGULAR,2265236,29115,-9.938900e+04,2.870300e+04,Saturday,6
3153830,S101A,R070,01-00-05,ST. GEORGE,1,SRT,2018-06-09,00:00:00,REGULAR,18375,1,-2.249992e+06,-2.911400e+04,Saturday,6
3153956,S101A,R070,01-03-01,ST. GEORGE,1,SRT,2018-06-09,00:00:00,REGULAR,1727509,205,-3.113600e+05,2.000000e+00,Saturday,6
3153998,S101A,R070,01-03-02,ST. GEORGE,1,SRT,2018-06-09,00:00:00,REGULAR,247761,10,-1.485973e+06,-1.950000e+02,Saturday,6
3154082,S101A,R070,01-05-00,ST. GEORGE,1,SRT,2018-06-09,00:00:00,REGULAR,817,0,-1.258346e+06,-2.030000e+02,Saturday,6
3154124,S101A,R070,01-05-01,ST. GEORGE,1,SRT,2018-06-09,00:00:00,REGULAR,536,0,-2.840000e+02,0.000000e+00,Saturday,6
3154250,S102,R165,00-03-00,TOMPKINSVILLE,1,SRT,2018-06-09,02:00:00,REGULAR,525664,15,-2.160700e+04,-4.279000e+03,Saturday,6
3154334,S102,R165,00-03-02,TOMPKINSVILLE,1,SRT,2018-06-09,02:00:00,REGULAR,235316,3,-7.193668e+06,-2.410679e+06,Saturday,6
3154418,S102,R165,00-05-01,TOMPKINSVILLE,1,SRT,2018-06-09,02:00:00,REGULAR,184,0,-2.621420e+05,-6.553600e+04,Saturday,6
3154634,TRAM2,R469,00-00-01,RIT-ROOSEVELT,R,RIT,2018-06-09,01:00:00,REGULAR,2614017,29286,-1.477611e+06,-2.954100e+04,Saturday,6
3154676,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,2018-06-09,01:00:00,REGULAR,553713,21398,-2.060304e+06,-7.888000e+03,Saturday,6

In [17]:
merged_data.iloc[3154530:3154560]

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,Ent,Ext,day_of_week,month
3154530,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-13,01:00:00,REGULAR,193842,2120,0.0,0.0,Wednesday,6
3154531,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-13,05:00:00,REGULAR,193842,2120,0.0,0.0,Wednesday,6
3154532,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-13,09:00:00,REGULAR,193842,2120,0.0,0.0,Wednesday,6
3154533,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-13,13:00:00,REGULAR,193842,2120,0.0,0.0,Wednesday,6
3154534,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-13,17:00:00,REGULAR,193842,2120,0.0,0.0,Wednesday,6
3154535,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-13,21:00:00,REGULAR,193842,2120,0.0,0.0,Wednesday,6
3154536,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-14,01:00:00,REGULAR,193842,2120,0.0,0.0,Thursday,6
3154537,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-14,05:00:00,REGULAR,193842,2120,0.0,0.0,Thursday,6
3154538,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-14,09:00:00,REGULAR,193842,2120,0.0,0.0,Thursday,6
3154539,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-14,13:00:00,REGULAR,193842,2120,0.0,0.0,Thursday,6
3154540,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-14,17:00:00,REGULAR,193842,2120,0.0,0.0,Thursday,6
3154541,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-14,21:00:00,REGULAR,193842,2120,0.0,0.0,Thursday,6
3154542,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-15,01:00:00,REGULAR,193842,2120,0.0,0.0,Friday,6
3154543,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-15,05:00:00,REGULAR,193842,2120,0.0,0.0,Friday,6
3154544,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-15,09:00:00,REGULAR,193894,2122,52.0,2.0,Friday,6
3154545,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-15,13:00:00,REGULAR,194211,2133,317.0,11.0,Friday,6
3154546,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-15,17:00:00,REGULAR,194629,2139,418.0,6.0,Friday,6
3154547,TRAM1,R468,00-00-01,RIT-MANHATTAN,R,RIT,2018-06-15,21:00:00,REGULAR,195063,2148,434.0,9.0,Friday,6
3154548,TRAM1,R468,00-00-02,RIT-MANHATTAN,R,RIT,2018-06-09,01:00:00,REGULAR,1844124,25338,1649061.0,23190.0,Saturday,6
3154549,TRAM1,R468,00-00-02,RIT-MANHATTAN,R,RIT,2018-06-09,05:00:00,REGULAR,1844162,25340,38.0,2.0,Saturday,6
3154550,TRAM1,R468,00-00-02,RIT-MANHATTAN,R,RIT,2018-06-09,09:00:00,REGULAR,1844282,25343,120.0,3.0,Saturday,6
3154551,TRAM1,R468,00-00-02,RIT-MANHATTAN,R,RIT,2018-06-09,12:37:40,REGULAR,1844967,25358,685.0,15.0,Saturday,6
3154552,TRAM1,R468,00-00-02,RIT-MANHATTAN,R,RIT,2018-06-09,12:39:00,REGULAR,1844970,25358,3.0,0.0,Saturday,6
3154553,TRAM1,R468,00-00-02,RIT-MANHATTAN,R,RIT,2018-06-09,13:00:00,REGULAR,1845076,25365,106.0,7.0,Saturday,6
3154554,TRAM1,R468,00-00-02,RIT-MANHATTAN,R,RIT,2018-06-09,17:00:00,REGULAR,1846018,25376,942.0,11.0,Saturday,6
3154555,TRAM1,R468,00-00-02,RIT-MANHATTAN,R,RIT,2018-06-09,21:00:00,REGULAR,1846950,25383,932.0,7.0,Saturday,6
3154556,TRAM1,R468,00-00-02,RIT-MANHATTAN,R,RIT,2018-06-10,01:00:00,REGULAR,1847409,25393,459.0,10.0,Sunday,6
3154557,TRAM1,R468,00-00-02,RIT-MANHATTAN,R,RIT,2018-06-10,05:00:00,REGULAR,1847468,25398,59.0,5.0,Sunday,6
3154558,TRAM1,R468,00-00-02,RIT-MANHATTAN,R,RIT,2018-06-10,09:00:00,REGULAR,1847730,25407,262.0,9.0,Sunday,6
3154559,TRAM1,R468,00-00-02,RIT-MANHATTAN,R,RIT,2018-06-10,13:00:00,REGULAR,1848293,25432,563.0,25.0,Sunday,6

In [18]:
merged_data.to_csv('cleaned_data_with_outliers.csv')