In [7]:
import pandas as pd
import matplotlib as mp
import seaborn as sns
import time

In [8]:
data1 = pd.read_csv('files/file1.csv')

In [9]:
data2 = pd.read_csv('files/file2.csv')

In [10]:
data3 = pd.read_csv('files/file3.csv')

In [11]:
data4 = pd.read_csv('files/file4.csv')

In [12]:
data5 = pd.read_csv('files/file5.csv')

In [13]:
data6 = pd.read_csv('files/file6.csv')

In [14]:
data7 = pd.read_csv('files/file7.csv')

In [15]:
data8 = pd.read_csv('files/file8.csv')

In [16]:
data9 = pd.read_csv('files/file9.csv')

In [17]:
data10 = pd.read_csv('files/file10.csv')

In [18]:
data11 = pd.read_csv('files/file11.csv')

In [19]:
data12 = pd.read_csv('files/file12.csv')

In [20]:
data13 = pd.read_csv('files/file13.csv')

In [21]:
data14 = pd.read_csv('files/file14.csv')

In [22]:
data15 = pd.read_csv('files/file15.csv')

In [23]:
data16 = pd.read_csv('files/file16.csv')

In [24]:
frames = [data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11, data12, data13, data14, data15, data16]

In [25]:
merg=pd.concat(frames)

In [26]:
merg['EXITS']=merg['EXITS                                                               ']

In [27]:
del merg['EXITS                                                               ']

In [28]:
merg.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/24/2018,03:00:00,RECOVR AUD,6527780,2210496
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/24/2018,07:00:00,REGULAR,6527794,2210507
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/24/2018,11:00:00,REGULAR,6527838,2210585
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/24/2018,15:00:00,REGULAR,6527994,2210644
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/24/2018,19:00:00,REGULAR,6528278,2210705

In [29]:
merg.dropna()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/24/2018,03:00:00,RECOVR AUD,6527780,2210496
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/24/2018,07:00:00,REGULAR,6527794,2210507
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/24/2018,11:00:00,REGULAR,6527838,2210585
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/24/2018,15:00:00,REGULAR,6527994,2210644
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/24/2018,19:00:00,REGULAR,6528278,2210705
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/24/2018,23:00:00,REGULAR,6528389,2210728
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/25/2018,03:00:00,REGULAR,6528417,2210734
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/25/2018,07:00:00,REGULAR,6528423,2210741
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/25/2018,11:00:00,REGULAR,6528468,2210788
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/25/2018,15:00:00,REGULAR,6528591,2210838
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/25/2018,19:00:00,REGULAR,6528785,2210886
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/25/2018,23:00:00,REGULAR,6528890,2210905
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/26/2018,03:00:00,REGULAR,6528905,2210907
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/26/2018,07:00:00,REGULAR,6528918,2210938
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/26/2018,11:00:00,REGULAR,6529053,2211138
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/26/2018,15:00:00,REGULAR,6529268,2211202
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/26/2018,19:00:00,REGULAR,6530018,2211256
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/26/2018,23:00:00,REGULAR,6530289,2211291
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/27/2018,03:00:00,REGULAR,6530309,2211297
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/27/2018,07:00:00,REGULAR,6530322,2211331
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/27/2018,11:00:00,REGULAR,6530462,2211629
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/27/2018,15:00:00,REGULAR,6530676,2211684
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/27/2018,19:00:00,REGULAR,6531460,2211753
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/27/2018,23:00:00,REGULAR,6531754,2211798
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/28/2018,03:00:00,REGULAR,6531774,2211800
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/28/2018,07:00:00,REGULAR,6531789,2211834
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/28/2018,11:00:00,REGULAR,6531942,2212145
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/28/2018,15:00:00,REGULAR,6532144,2212219
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/28/2018,19:00:00,REGULAR,6532892,2212288
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,02/28/2018,23:00:00,REGULAR,6533209,2212318
...,...,...,...,...,...,...,...,...,...,...,...
196948,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/11/2018,01:00:00,REGULAR,2926189,387127
196949,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/11/2018,05:00:00,REGULAR,2926193,387128
196950,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/11/2018,09:00:00,REGULAR,2926460,387132
196951,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/11/2018,13:00:00,REGULAR,2926833,387138
196952,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/11/2018,17:00:00,REGULAR,2927310,387147
196953,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/11/2018,21:00:00,REGULAR,2927754,387152
196954,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/12/2018,01:00:00,REGULAR,2927908,387160
196955,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/12/2018,05:00:00,REGULAR,2927912,387162
196956,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/12/2018,09:00:00,REGULAR,2928224,387164
196957,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/12/2018,13:00:00,REGULAR,2928511,387177
196958,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/12/2018,17:00:00,REGULAR,2928954,387181
196959,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/12/2018,21:00:00,REGULAR,2929296,387185
196960,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/13/2018,01:00:00,REGULAR,2929512,387188
196961,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/13/2018,05:00:00,REGULAR,2929515,387188
196962,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/13/2018,09:00:00,REGULAR,2929829,387194
196963,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/13/2018,13:00:00,REGULAR,2930206,387199
196964,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/13/2018,17:00:00,REGULAR,2930507,387203
196965,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/13/2018,21:00:00,REGULAR,2930914,387209
196966,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/14/2018,01:00:00,REGULAR,2931064,387212
196967,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/14/2018,05:00:00,REGULAR,2931068,387212
196968,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/14/2018,09:00:00,REGULAR,2931353,387214
196969,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/14/2018,13:00:00,REGULAR,2931756,387219
196970,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/14/2018,17:00:00,REGULAR,2932222,387224
196971,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/14/2018,21:00:00,REGULAR,2932697,387229
196972,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/15/2018,01:00:00,REGULAR,2932873,387232
196973,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/15/2018,05:00:00,REGULAR,2932882,387232
196974,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/15/2018,09:00:00,REGULAR,2933103,387236
196975,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/15/2018,13:00:00,REGULAR,2933526,387242
196976,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/15/2018,17:00:00,REGULAR,2933990,387247
196977,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,06/15/2018,21:00:00,REGULAR,2934393,387256

In [30]:
merg.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3154761 entries, 0 to 196977
Data columns (total 11 columns):
C/A         object
UNIT        object
SCP         object
STATION     object
LINENAME    object
DIVISION    object
DATE        object
TIME        object
DESC        object
ENTRIES     int64
EXITS       int64
dtypes: int64(2), object(9)
memory usage: 288.8+ MB

In [31]:
merg.to_csv('merg_data.csv')

In [32]:
merg['Ent'] = merg['ENTRIES'] - merg['ENTRIES'].shift(+1)

In [33]:
merg['Ext'] = merg['EXITS'] - merg['EXITS'].shift(+1)

In [38]:
merg.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,Ent,Ext,day_of_week,month
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,03:00:00,RECOVR AUD,6527780,2210496,NaN,NaN,Saturday,2
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,07:00:00,REGULAR,6527794,2210507,14.0,11.0,Saturday,2
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,11:00:00,REGULAR,6527838,2210585,44.0,78.0,Saturday,2
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,15:00:00,REGULAR,6527994,2210644,156.0,59.0,Saturday,2
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,19:00:00,REGULAR,6528278,2210705,284.0,61.0,Saturday,2

In [35]:
merg.describe()

            ENTRIES         EXITS           Ent           Ext
count  3.154761e+06  3.154761e+06  3.154760e+06  3.154760e+06
mean   3.927402e+07  3.232717e+07 -1.139037e+00 -5.779330e-01
std    2.050674e+08  1.900460e+08  4.288098e+07  3.929465e+07
min    0.000000e+00  0.000000e+00 -2.117750e+09 -2.145033e+09
25%    5.081950e+05  2.482710e+05  9.000000e+00  7.000000e+00
50%    2.577976e+06  1.454429e+06  7.400000e+01  5.100000e+01
75%    6.890224e+06  4.826487e+06  2.510000e+02  1.700000e+02
max    2.130068e+09  2.145850e+09  2.122404e+09  2.145033e+09

In [36]:
merg['DATE']=pd.to_datetime(merg['DATE'])
merg['day_of_week'] = merg['DATE'].dt.weekday_name

In [37]:
merg['month']=merg['DATE'].dt.month

In [39]:
merg.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,Ent,Ext,day_of_week,month
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,03:00:00,RECOVR AUD,6527780,2210496,NaN,NaN,Saturday,2
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,07:00:00,REGULAR,6527794,2210507,14.0,11.0,Saturday,2
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,11:00:00,REGULAR,6527838,2210585,44.0,78.0,Saturday,2
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,15:00:00,REGULAR,6527994,2210644,156.0,59.0,Saturday,2
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,19:00:00,REGULAR,6528278,2210705,284.0,61.0,Saturday,2

In [40]:
merg.dropna(axis=0)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,Ent,Ext,day_of_week,month
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,07:00:00,REGULAR,6527794,2210507,14.0,11.0,Saturday,2
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,11:00:00,REGULAR,6527838,2210585,44.0,78.0,Saturday,2
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,15:00:00,REGULAR,6527994,2210644,156.0,59.0,Saturday,2
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,19:00:00,REGULAR,6528278,2210705,284.0,61.0,Saturday,2
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-24,23:00:00,REGULAR,6528389,2210728,111.0,23.0,Saturday,2
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-25,03:00:00,REGULAR,6528417,2210734,28.0,6.0,Sunday,2
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-25,07:00:00,REGULAR,6528423,2210741,6.0,7.0,Sunday,2
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-25,11:00:00,REGULAR,6528468,2210788,45.0,47.0,Sunday,2
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-25,15:00:00,REGULAR,6528591,2210838,123.0,50.0,Sunday,2
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-25,19:00:00,REGULAR,6528785,2210886,194.0,48.0,Sunday,2
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-25,23:00:00,REGULAR,6528890,2210905,105.0,19.0,Sunday,2
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-26,03:00:00,REGULAR,6528905,2210907,15.0,2.0,Monday,2
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-26,07:00:00,REGULAR,6528918,2210938,13.0,31.0,Monday,2
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-26,11:00:00,REGULAR,6529053,2211138,135.0,200.0,Monday,2
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-26,15:00:00,REGULAR,6529268,2211202,215.0,64.0,Monday,2
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-26,19:00:00,REGULAR,6530018,2211256,750.0,54.0,Monday,2
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-26,23:00:00,REGULAR,6530289,2211291,271.0,35.0,Monday,2
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-27,03:00:00,REGULAR,6530309,2211297,20.0,6.0,Tuesday,2
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-27,07:00:00,REGULAR,6530322,2211331,13.0,34.0,Tuesday,2
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-27,11:00:00,REGULAR,6530462,2211629,140.0,298.0,Tuesday,2
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-27,15:00:00,REGULAR,6530676,2211684,214.0,55.0,Tuesday,2
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-27,19:00:00,REGULAR,6531460,2211753,784.0,69.0,Tuesday,2
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-27,23:00:00,REGULAR,6531754,2211798,294.0,45.0,Tuesday,2
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-28,03:00:00,REGULAR,6531774,2211800,20.0,2.0,Wednesday,2
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-28,07:00:00,REGULAR,6531789,2211834,15.0,34.0,Wednesday,2
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-28,11:00:00,REGULAR,6531942,2212145,153.0,311.0,Wednesday,2
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-28,15:00:00,REGULAR,6532144,2212219,202.0,74.0,Wednesday,2
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-28,19:00:00,REGULAR,6532892,2212288,748.0,69.0,Wednesday,2
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-02-28,23:00:00,REGULAR,6533209,2212318,317.0,30.0,Wednesday,2
30,A002,R051,02-00-00,59 ST,NQR456W,BMT,2018-03-01,03:00:00,REGULAR,6533215,2212327,6.0,9.0,Thursday,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196948,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-11,01:00:00,REGULAR,2926189,387127,151.0,6.0,Monday,6
196949,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-11,05:00:00,REGULAR,2926193,387128,4.0,1.0,Monday,6
196950,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-11,09:00:00,REGULAR,2926460,387132,267.0,4.0,Monday,6
196951,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-11,13:00:00,REGULAR,2926833,387138,373.0,6.0,Monday,6
196952,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-11,17:00:00,REGULAR,2927310,387147,477.0,9.0,Monday,6
196953,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-11,21:00:00,REGULAR,2927754,387152,444.0,5.0,Monday,6
196954,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-12,01:00:00,REGULAR,2927908,387160,154.0,8.0,Tuesday,6
196955,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-12,05:00:00,REGULAR,2927912,387162,4.0,2.0,Tuesday,6
196956,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-12,09:00:00,REGULAR,2928224,387164,312.0,2.0,Tuesday,6
196957,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-12,13:00:00,REGULAR,2928511,387177,287.0,13.0,Tuesday,6
196958,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-12,17:00:00,REGULAR,2928954,387181,443.0,4.0,Tuesday,6
196959,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-12,21:00:00,REGULAR,2929296,387185,342.0,4.0,Tuesday,6
196960,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-13,01:00:00,REGULAR,2929512,387188,216.0,3.0,Wednesday,6
196961,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-13,05:00:00,REGULAR,2929515,387188,3.0,0.0,Wednesday,6
196962,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-13,09:00:00,REGULAR,2929829,387194,314.0,6.0,Wednesday,6
196963,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-13,13:00:00,REGULAR,2930206,387199,377.0,5.0,Wednesday,6
196964,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-13,17:00:00,REGULAR,2930507,387203,301.0,4.0,Wednesday,6
196965,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-13,21:00:00,REGULAR,2930914,387209,407.0,6.0,Wednesday,6
196966,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-14,01:00:00,REGULAR,2931064,387212,150.0,3.0,Thursday,6
196967,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-14,05:00:00,REGULAR,2931068,387212,4.0,0.0,Thursday,6
196968,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-14,09:00:00,REGULAR,2931353,387214,285.0,2.0,Thursday,6
196969,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-14,13:00:00,REGULAR,2931756,387219,403.0,5.0,Thursday,6
196970,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-14,17:00:00,REGULAR,2932222,387224,466.0,5.0,Thursday,6
196971,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-14,21:00:00,REGULAR,2932697,387229,475.0,5.0,Thursday,6
196972,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-15,01:00:00,REGULAR,2932873,387232,176.0,3.0,Friday,6
196973,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-15,05:00:00,REGULAR,2932882,387232,9.0,0.0,Friday,6
196974,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-15,09:00:00,REGULAR,2933103,387236,221.0,4.0,Friday,6
196975,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-15,13:00:00,REGULAR,2933526,387242,423.0,6.0,Friday,6
196976,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-15,17:00:00,REGULAR,2933990,387247,464.0,5.0,Friday,6
196977,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,2018-06-15,21:00:00,REGULAR,2934393,387256,403.0,9.0,Friday,6

In [41]:
merg.to_csv('merg_data.csv')